name: saargress_app
version: 0.0.1
description: The Saargress web app.
dependencies:
  browser: any
  googleapis_auth: ">=0.2.0 <0.3.0"
  #google_oauth2_client: ">=0.4.1 <0.5.0"
  googleapis: ">=0.3.0 <0.4.0"
  polymer: ">=0.15.0+1 <0.16.0"
  core_elements: ">=0.4.0+2 <0.5.0"
  intl: ">=0.11.9 <0.12.0"
transformers:
- polymer:
    #inline_stylesheets:
    #  web/css/bootstrap.min.css: false
    entry_points:
      - web/saargress.html