name: saargress
version: 0.0.1
description: The Saargress server app.
dependencies:
  path: ">=1.2.0 <2.0.0"
  http: ">=0.11.1+1 <0.12.0"
  uuid: ">=0.4.1 <0.5.0"
  shelf: ">=0.5.5 <0.6.0"
  shelf_auth: ">=0.1.0+1 <0.2.0"
  shelf_rest: ">=0.1.3+1 <0.2.0"
  googleapis_auth: ">=0.1.0 <0.2.0"
  #json_schema: ">=1.0.0 <2.0.0"
dev_dependencies:
  unittest: any
